#ifndef TICTACTOE_MOVEEXCEPTIONREASONS_H
#define TICTACTOE_MOVEEXCEPTIONREASONS_H

struct MoveExceptionReasons
{
    enum REASONS
    {
        INVALID_GAME_STATUS,
        INVALID_MOVE_CELL,
        UNDEFINED_REASON
    };
};

#endif //TICTACTOE_MOVEEXCEPTIONREASONS_H
